service: unive-micro-service

plugins:
  - serverless-offline
  # - serverless-dynamodb-local
frameworkVersion: '2'

custom:
  serverless-offline:
    httpPort: 4001

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1

# yo
functions:
  all:
    handler: notifications.all
    events:
      - http:
          path: notifications
          method: get
  
  create:
    handler: notifications.create
    events:
      - http:
          path: notifications
          method: post

  update:
    handler: notifications.update
    events:
      - http:
          path: notifications/{id}
          method: put
  
  find:
    handler: notifications.find
    events:
      - http:
          path: notifications/{id}
          method: get
          
  delete:
    handler: notifications.delete
    events:
      - http:
          path: notifications/{id}
          method: delete

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
